USE Infinity

SELECT	perpes.id,		
		perpaf.perPersonIdFather,
		perpaf.idCardFather,
		perpaf.perTitlePrefixIdFather,
		perpaf.firstNameFather,
		perpaf.lastNameFather,
		perpaf.perMaritalStatusIdFather,
		perpaf.peraddPersonIdFather,
		perpaf.plcCountryIdPermanentFather,
		perpaf.noPermanentFather,
		perpaf.phoneNumberPermanentFather,
		perpaf.mobileNumberPermanentFather,
		perpaf.plcCountryIdCurrentFather,
		perpaf.noCurrentFather,
		perpaf.phoneNumberCurrentFather,
		perpaf.mobileNumberCurrentFather,
		perpaf.perworPersonIdFather,
		perpaf.occupationFather,
		perpam.perPersonIdMother,
		perpam.idCardMother,
		perpam.perTitlePrefixIdMother,
		perpam.firstNameMother,
		perpam.lastNameMother,
		perpam.perMaritalStatusIdMother,
		perpam.peraddPersonIdMother,
		perpam.plcCountryIdPermanentMother,
		perpam.noPermanentMother,
		perpam.phoneNumberPermanentMother,
		perpam.mobileNumberPermanentMother,
		perpam.plcCountryIdCurrentMother,
		perpam.noCurrentMother,
		perpam.phoneNumberCurrentMother,
		perpam.mobileNumberCurrentMother,
		perpam.perworPersonIdMother,
		perpam.occupationMother,
		perpar.perRelationshipId,
		perpap.perPersonIdParent,
		perpap.idCardParent,
		perpap.perTitlePrefixIdParent,
		perpap.firstNameParent,
		perpap.lastNameParent,
		perpap.perMaritalStatusIdParent,
		perpap.peraddPersonIdParent,
		perpap.plcCountryIdPermanentParent,
		perpap.noPermanentParent,
		perpap.phoneNumberPermanentParent,
		perpap.mobileNumberPermanentParent,
		perpap.plcCountryIdCurrentParent,
		perpap.noCurrentParent,
		perpap.phoneNumberCurrentParent,
		perpap.mobileNumberCurrentParent,
		perpap.perworPersonIdParent,
		perpap.occupationParent
FROM	perPerson AS perpes INNER JOIN
		perParent AS perpar ON perpes.id = perpar.perPersonId LEFT JOIN
		perRelationship AS perrel ON perpar.perRelationshipId = perrel.id LEFT JOIN
		(SELECT	perpar.perPersonId,
				perpar.perPersonIdFather,
				perpes.idCard AS idCardFather,
				perpes.perTitlePrefixId AS perTitlePrefixIdFather,
				perpes.firstName AS firstNameFather,
				perpes.lastName AS lastNameFather,
				perpes.perMaritalStatusId AS perMaritalStatusIdFather,
				peradd.perPersonId AS peraddPersonIdFather,
				peradd.plcCountryIdPermanent AS plcCountryIdPermanentFather,
				peradd.noPermanent AS noPermanentFather,
				peradd.phoneNumberPermanent AS phoneNumberPermanentFather,
				peradd.mobileNumberPermanent AS mobileNumberPermanentFather,
				peradd.plcCountryIdCurrent AS plcCountryIdCurrentFather,
				peradd.noCurrent AS noCurrentFather,
				peradd.phoneNumberCurrent AS phoneNumberCurrentFather,
				peradd.mobileNumberCurrent AS mobileNumberCurrentFather,
				perwor.perPersonId AS perworPersonIdFather,
				perwor.occupation AS occupationFather
		 FROM	perParent AS perpar INNER JOIN
				perPerson AS perpes ON perpar.perPersonIdFather = perpes.id LEFT JOIN
				perAddress AS peradd ON perpar.perPersonIdFather = peradd.perPersonId LEFT JOIN
				perWork AS perwor ON perpar.perPersonIdFather = perwor.perPersonId) AS perpaf ON perpes.id = perpaf.perPersonId LEFT JOIN
		(SELECT	perpar.perPersonId,
				perpar.perPersonIdMother,
				perpes.idCard AS idCardMother,
				perpes.perTitlePrefixId AS perTitlePrefixIdMother,
				perpes.firstName AS firstNameMother,
				perpes.lastName AS lastNameMother,
				perpes.perMaritalStatusId AS perMaritalStatusIdMother,
				peradd.perPersonId AS peraddPersonIdMother,
				peradd.plcCountryIdPermanent AS plcCountryIdPermanentMother,
				peradd.noPermanent AS noPermanentMother,
				peradd.phoneNumberPermanent AS phoneNumberPermanentMother,
				peradd.mobileNumberPermanent AS mobileNumberPermanentMother,
				peradd.plcCountryIdCurrent AS plcCountryIdCurrentMother,
				peradd.noCurrent AS noCurrentMother,
				peradd.phoneNumberCurrent AS phoneNumberCurrentMother,
				peradd.mobileNumberCurrent AS mobileNumberCurrentMother,
				perwor.perPersonId AS perworPersonIdMother,
				perwor.occupation AS occupationMother
		 FROM	perParent AS perpar INNER JOIN
				perPerson AS perpes ON perpar.perPersonIdMother = perpes.id LEFT JOIN
				perAddress AS peradd ON perpar.perPersonIdMother = peradd.perPersonId LEFT JOIN
				perWork AS perwor ON perpar.perPersonIdMother = perwor.perPersonId) AS perpam ON perpes.id = perpam.perPersonId LEFT JOIN
		(SELECT	perpar.perPersonId,
				perpar.perPersonIdParent,
				perpes.idCard AS idCardParent,
				perpes.perTitlePrefixId AS perTitlePrefixIdParent,
				perpes.firstName AS firstNameParent,
				perpes.lastName AS lastNameParent,
				perpes.perMaritalStatusId AS perMaritalStatusIdParent,
				peradd.perPersonId AS peraddPersonIdParent,
				peradd.plcCountryIdPermanent AS plcCountryIdPermanentParent,
				peradd.noPermanent AS noPermanentParent,
				peradd.phoneNumberPermanent AS phoneNumberPermanentParent,
				peradd.mobileNumberPermanent AS mobileNumberPermanentParent,
				peradd.plcCountryIdCurrent AS plcCountryIdCurrentParent,
				peradd.noCurrent AS noCurrentParent,
				peradd.phoneNumberCurrent AS phoneNumberCurrentParent,
				peradd.mobileNumberCurrent AS mobileNumberCurrentParent,
				perwor.perPersonId AS perworPersonIdParent,
				perwor.occupation AS occupationParent
		 FROM	perParent AS perpar INNER JOIN
				perPerson AS perpes ON perpar.perPersonIdParent = perpes.id LEFT JOIN
				perAddress AS peradd ON perpar.perPersonIdParent = peradd.perPersonId LEFT JOIN
				perWork AS perwor ON perpar.perPersonIdParent = perwor.perPersonId) AS perpap ON perpes.id = perpap.perPersonId
